# Discrepancies in `r last_year`

```{r, echo=FALSE}
number_of_economies = 10
economies_estimated_with_cpi = ""
if (enable_estimate_last_year) {
  estimated_with_cpi = read_csv(file.path(outputdir, "estimated_with_cpi.csv"), show_col_types = FALSE)
  economies_estimated_with_cpi = estimated_with_cpi %>% 
    left_join(labels,
              by = join_by(Country_Code == Code)) %>% 
    pull(Label) %>%  
    paste(collapse = ", ") %>% 
    paste0(".")
}
```

```{asis, echo = enable_estimate_last_year}
Real GDP was estimated using CPI for the following economies:
```
`r economies_estimated_with_cpi`

Table of discrepancies in real GDP arranged by the log of ratio in the year `r last_year`.

```{r, echo=FALSE, message=FALSE}
estimate_discrepancies = unctaddf %>%
  filter(
    str_length(Code) < 4,
    Year == last_year
  ) %>% 
  arrange(desc(abs(log(Value.new/Value.old))))

estimate_discrepancies %>% 
  filter(Variable == "GDP_at_current_prices") %>% 
  transmute(
    Code = Code,
    Label = Economy_Label.old,
    Old_Value = format(Value.old, digits = 3, scientific = TRUE),
    New_Value = format(Value.new, digits = 3, scientific = TRUE),
    Diff = format(Value.new - Value.old, digits = 3, scientific = TRUE),
    Ratio = format(Value.new / Value.old, digits = 3)
  ) %>% 
  DT::datatable()
```


Plots of the `r number_of_economies` biggest discrepancies.

```{r, echo=FALSE, message=FALSE}
estimate_discrepancies %>% 
  head(number_of_economies) %>% 
  distinct(Economy_Label.new) %>% 
  pull() %>% 
  map(plot_by_economy) %>% 
  compact() %>% 
  map(ggplotly, dynamicTicks = TRUE) %>% 
  map(layout, title = list(
                font = list(
                  size = 22)),
              legend = list(
                orientation = "h",
                title = ""),
              margin = list(
                b=110
              )) %>% 
  htmltools::tagList() 
```